name: Hadolint
on:
  push:
    branches: [main, develop]
    paths: ['app/Dockerfile']
  pull_request:
    branches: [main]
    paths: ['app/Dockerfile']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: app/Dockerfile
